"""empty message

Revision ID: 6dbb9feaf514
Revises: 2457c90e00c5
Create Date: 2019-06-11 16:24:33.217610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dbb9feaf514'
down_revision = '2457c90e00c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genre_genre_name'), 'genre', ['genre_name'], unique=True)
    op.create_table('genre_games',
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre_games')
    op.drop_index(op.f('ix_genre_genre_name'), table_name='genre')
    op.drop_table('genre')
    # ### end Alembic commands ###
