"""empty message

Revision ID: 71e5e8993365
Revises: 1b4b8b1fcfaa
Create Date: 2019-06-08 00:38:28.584533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e5e8993365'
down_revision = '1b4b8b1fcfaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_name', sa.String(length=128), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_game_name'), 'game', ['game_name'], unique=True)
    op.create_index(op.f('ix_game_release_date'), 'game', ['release_date'], unique=False)
    op.create_table('platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_platform_name'), 'platform', ['platform_name'], unique=True)
    op.add_column('rating', sa.Column('game_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rating', 'game', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.drop_column('rating', 'game_id')
    op.drop_index(op.f('ix_platform_platform_name'), table_name='platform')
    op.drop_table('platform')
    op.drop_index(op.f('ix_game_release_date'), table_name='game')
    op.drop_index(op.f('ix_game_game_name'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
