"""empty message

Revision ID: 887b40ecec38
Revises: 6dbb9feaf514
Create Date: 2019-06-12 01:01:17.541029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887b40ecec38'
down_revision = '6dbb9feaf514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_company_name'), 'company', ['company_name'], unique=True)
    op.create_table('developer_games',
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], )
    )
    op.create_table('publisher_games',
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['company.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publisher_games')
    op.drop_table('developer_games')
    op.drop_index(op.f('ix_company_company_name'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
